### ISSUE TITLE
[BUG]: Production DFP: GPU memory allocation during training seems too high

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/Morpheus#725] opened 2023-02-21 19:15 UTC
### Version

23.01

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

We recently filtered out some data and assigned it to a new account number and for some reason during training this blows up memory wise. For a 3gb 24 hour sample, `dfencoder` tries to allocate >100gb of memory during training.

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment] 2023-08-22 00:20
Closing as duplicate of #933

**Closed by mdemoret-nv** 2023-08-22 00:20 UTC
Labels: bug, dfp
